name: Daily PTF Data Update

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run update script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        EPIAS_USERNAME: ${{ secrets.EPIAS_USERNAME }}
        EPIAS_PASSWORD: ${{ secrets.EPIAS_PASSWORD }}
      run: |
        python -c "
        import os
        print('Environment variables:')
        print('SUPABASE_URL exists:', bool(os.getenv('SUPABASE_URL')))
        print('SUPABASE_KEY exists:', bool(os.getenv('SUPABASE_KEY')))
        print('EPIAS_USERNAME exists:', bool(os.getenv('EPIAS_USERNAME')))
        print('EPIAS_PASSWORD exists:', bool(os.getenv('EPIAS_PASSWORD')))
        "
        python update_next_day.py
